spring:
  application:
    name: DistribuitionCenter
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/cd}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    org.hibernate.sql: debug
    org.springframework: info

cd:
  id: 1
  name: "nha"
  url: ${CD_URL:http://localhost:6981}

hub:
  address: ${HUB_ADDRESS:http://localhost:8080}