spring:
  application:
    name: DistribuitionCenter
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cd
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 6981
logging:
  level:
    root: info
    org.hibernate.sql: debug
    org.springframework: info

cd:
  id: 1
  name: "pedro"
  url: "http://10.1.6.196:6981"

hub:
  address: "http://10.1.6.194:6980"